config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/contact', to: 'index#contact'
  get '/team', to: 'index#team'
  get '/welcome/:name', to: 'index#welcome'

  resources :gossips do
    resources :comments
    resources :likes
  end
  resources :users
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :gossip
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create, :new]
  def create
    @user = User.find_by(id: session[:user_id])
    @comment = Comment.new(post_params)
    @comment.gossip_id = params[:gossip_id]
    @comment.user_id = @user.id

    if @comment.save
      flash[:notice] = "New comment Save in DB"
      redirect_to gossip_path(@comment.gossip_id)
    else
      puts @comment.errors.messages
      puts "error comments"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(post_params)
      flash[:notice] = "Comments updated in DB"
      redirect_to gossip_path(params[:gossip_id])
    else
      flash.now[:alert] = "We cannot updated this comments for this reason(s) :"
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Comment deleted in DB"
      redirect_to gossip_path(params[:gossip_id]) 
    else 
      flash.now[:alert] = "We cannot deleted this comment for this reason(s) :"
      render :edit
    end
  end

  private
  def post_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:alert] = "You need to login in order to see all gossips !"
      redirect_to new_session_path
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1> Comment n° <%= @comment.id %></h1> 
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p><%= alert %></p>
        <ul class="list-unstyled">
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      
    <% end %>
  </div>
  <%= form_for [@gossip, @comment] do |f| %>
    <div class="form-group">
      <label>Content</label>
      <%= f.text_area :content, class: 'form-control'%>
    </div>
    <div class="form-group">
      <button  class="btn btn-secondary" type="submit">Update</button>
    </div>
  <% end %>
  <div class="d-flex">
    <%= link_to "Back" , gossip_path(params[:gossip_id]), :class => "btn-custom"%>
    <%= link_to "Delete this comment" , gossip_comment_path(params[:gossip_id], params[:id]), :method => "delete", :class => "btn-custom-delete mx-auto", :data => {:confirm => "are_you_sure"} %>
  </div>
</div>