config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/contact', to: 'index#contact'
  get '/team', to: 'index#team'
  get '/welcome/:name', to: 'index#welcome'

  resources :gossips do
    resources :comments
    resources :likes
  end
  resources :users
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord

  validates :name, presence: true
  validates :zip_code, presence: true

  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title, presence: true, length: { in: 3..14, message: "Please enter between 3 to 14 characters" }
  validates :content, presence: true

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips

end

app/models/jt_pm_recipient.rb
class JtPmRecipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord

  validates :content, presence: true, length: { in: 2..140 }
  
  belongs_to :sender, class_name: "User"
  has_many :jt_pm_recipients
  has_many :recipients, through: :jt_pm_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :title, presence: true, length: { in: 2..14 }

  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :description, presence: true
  validates :age, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :jt_pm_recipients
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage", through: :jt_pm_recipients

  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update_attribute(:remember_digest, remember_digest)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    
  def home
    @gossips = Gossip.all
  end

  def contact
  end

  def team
  end

  def welcome
  end

  def user
    @user = User.all.find_by(id:params[:id])
  end

  def gossip
    @gossip = Gossip.all.find_by(id:params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_gossip
  before_action :find_like, only: [:destroy]
  def create
    if already_liked?
      flash[:alert] = "You can't like more than once"
    else
      @gossip.likes.create(user_id: current_user.id)
    end
    redirect_back(fallback_location: gossips_path)
  end

  def destroy
    if !(already_liked?)
      flash[:alert] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_back(fallback_location: gossips_path)
  end
  private
  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end
  def already_liked?
    Like.where(user_id: current_user.id, gossip_id:
    params[:gossip_id]).exists?
  end
  def find_like
    @like = @gossip.likes.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
  def tag?(gossip)
    gossip.tags.length > 0 ? true : false
  end

  def gossips?(user)
    user.gossips.length > 0 ? true : false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user_id]
      # même chose que hier
      current_user = User.find_by(id: session[:user_id])
  
    # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
    elsif cookies[:user_id]
  
      # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
      user = User.find_by(id: cookies[:user_id])
  
      if user
  
        # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
        remember_token = cookies[:remember_token]
        remember_digest = user.remember_digest
        user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  
        # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
        if user_authenticated
          log_in user
          current_user = user
        end
  
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

  def is_creator?(gossip)
    current_user = User.find_by(id: session[:user_id])
    if gossip.user.id == current_user.id
      return true
    else
      return false
    end
  end
  def is_comment_creator?(comment)
    current_user = User.find_by(id: session[:user_id])
    if comment.user.id == current_user.id
      return true
    else
      return false
    end
  end

  def logged_in?
    if current_user
      return true
    else
      return false
    end
  end

  def remember(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end

  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end
end

app/helpers/users_helper.rb
require 'faker'

module UsersHelper
  def zipcode
    Faker::Address.zip_code
  end
end

app/views/index/contact.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>Contact Us</h1>
    <p>Keep in touch !</p>
    <img class="img-fluid img-goss" src="https://cranmerpreschool-aslockton.co.uk/wp-content/uploads/2019/02/email-us.png">
    <h2>To blablabla@gmail.com</h2>
  </div>
</div>

app/views/index/home.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>Welcome my Friend</h1>
    <p>Do you want some gossips ?????</p>
    <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
    <% end %>
  </div>

  <div class="text-center p-2 m-2">
    <h2> ⬇️ This is the last Gossips that we heard ⬇️ </h2> 
  </div>

  <div class="row justify-content-center">
    <% @gossips.each do |gossip| %>

      <div class="card gossip-card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.user.first_name%></h5>
          <p class="card-text"><%= gossip.title%></p>
          <div class="row justify-content-center">
            <div class="btn-custom"><%= link_to "See this gossip", gossip_path(gossip.id)%></div>
          </div>
        </div>
      </div>
    
    <% end %>
  </div>

</div>

app/views/index/team.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>GREAT TEAM EVER</h1>
    <p>Do you want to progress in your THP formation ? JOINS US</p>
    <%= image_tag "team.jpg", :class => "img-fluid img-goss" %>
    <h2>⬇️ Who is in the Game ? ⬇️</h2>
  </div>
  <div class="row justify-content-center text-center">
    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Vanak aka vanak lay in discord</h5>
        <div class="row justify-content-center">
          <div class="btn-custom"><%= link_to "See his github", "https://github.com/vanaklay" %></div>
        </div>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Maxime aka Mixmo in discord</h5>
        <div class="row justify-content-center">
          <div class="btn-custom"><%= link_to "See his github", "https://github.com/Mtwod" %></div>
        </div>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Coline aka in colinebrlt discord</h5>
        <div class="row justify-content-center">
          <div class="btn-custom"><%= link_to "See her github", "https://github.com/colinebrlt" %></div>
        </div>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Arthur aka Rud in discord</h5>
        <div class="row justify-content-center">
          <div class="btn-custom"><%= link_to "See his github", "https://github.com/Rudyar" %></div>
        </div>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Marie aka Marie Dechaux in discord</h5>
        <div class="row justify-content-center">
          <div class="btn-custom"><%= link_to "See her github", "https://github.com/mariedx" %></div>
        </div>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Flavien aka Flavien Loiseau in discord</h5>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Clémentine aka Clémentique Fouqué in discord</h5>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Aimery aka Aimery Cayol in discord</h5>
      </div>
    </div>

    <div class="card gossip-card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Martin aka Martin Louvard in discord</h5>
      </div>
    </div>

       
    
  </div>
</div>

app/views/index/welcome.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>Hello <%= params[:name].capitalize %></h1>
    <h2 class="p-2 m-2">This our greatest site of gossips ! Nice isn't it ?? 😝</h2>
    <img class="img-fluid img-goss" alt="Responsive image" src="https://www.avenir-sante.com/wp-content/uploads/2018/11/gossip-time-nico.png">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=News+Cycle&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "The Gossip Project", root_path , :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path , :class => "nav-item nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ze Team", team_path, :class => "nav-item nav-link" %>
            
          </li>
          <li class="nav-item">
            <%= link_to "Contact us", contact_path, :class => "nav-item nav-link" %>
          </li>
        </ul>
        
        <ul class="navbar-nav ml-auto">
          <% if logged_in? %> 
              <h3 class="nav-item nav-link"><%= current_user.first_name.capitalize %></h3>
            <li class="nav-item align-self-center">
              <%= link_to "Log out", session_path(session.id), method: :delete, :class => "nav-item nav-link" %>
            </li>
          <% else %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Login
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Login", new_session_path, :class => "dropdown-item" %>
                <%= link_to "Sign up", new_user_path, :class => "dropdown-item" %>
              </div>
            </div>
          <% end %>
          
        </ul>
      </div>
    </nav>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>