config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  get '/contact', to: 'index#contact'
  get '/team', to: 'index#team'
  get '/welcome/:name', to: 'index#welcome'

  resources :gossips do
    resources :comments
    resources :likes
  end
  resources :users
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :title, presence: true, length: { in: 3..14, message: "Please enter between 3 to 14 characters" }
  validates :content, presence: true

  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show, :new, :create]

  def index
    @gossips = Gossip.all
  end
    
  def new
    @gossip = Gossip.new
    @tags = Tag.all
  end

  def create
    @gossip = Gossip.create(title: params[:title], content: params[:content])
    @gossip.user = User.find_by(id: session[:user_id])
    JoinTableTagGossip.create(gossip: @gossip, tag: Tag.find_by(id: params[:tag]))
    if @gossip.save
      flash[:notice] = "New gossip Save in DB"
      redirect_to root_path 
    else
      flash.now[:alert] = "We cannot create your gossip for this reason(s) :"
      render :new
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    JoinTableTagGossip.update(tag: Tag.find(params[:gossip][:tags]))
    if @gossip.update(post_params)
      flash[:notice] = "Gossip updated in DB"
      redirect_to gossip_path(@gossip.id)
    else
      flash.now[:alert] = "We cannot updated this gossip for this reason(s) :"
      render :edit
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.all.sample
    @comment = Comment.new
    @comment.gossip_id = @gossip.id
    @comment.user_id = @user.id
    
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      puts "destroy ok"
      redirect_to gossips_path 
    else 
      puts "destroy errors"
    end
  end

  private
  def post_params
    post_params = params.require(:gossip).permit(:title, :content)
  end
  def authenticate_user
    unless current_user
      flash[:alert] = "You need to login in order to see all gossips !"
      redirect_to new_session_path
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
  def tag?(gossip)
    gossip.tags.length > 0 ? true : false
  end

  def gossips?(user)
    user.gossips.length > 0 ? true : false
  end
end

app/views/gossips/_comment.html.erb
<div class="card gossip-card" style="width: auto;">
  <div class="card-body">
    <h4>Comment by <%= comment.user.first_name + " " + comment.user.last_name %></h4>
    <hr/>
    <p><%= comment.content %></p>
    <% if is_comment_creator?(comment) %>
      <div class="row justify-content-center">
        <%= link_to "Edit this comment", edit_gossip_comment_path(@gossip.id, comment.id), :class => "btn-custom-edit m-3"%>
        <% if is_creator?(@gossip) %>
          <%= link_to "Delete this gossip" , gossip_path(@gossip.id), :method => "delete", :class => "btn-custom-delete m-3", :data => {:confirm => "are_you_sure"} %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/_form.html.erb
<div>
  <h3>Post a Comment</h3>
  <%= form_for [ @gossip, @comment ] do |f| %>
    <div class="form-group">
      <label>Content</label>
      <%= f.text_area :content, class: 'form-control'%>
    </div>
    <div class="form-group d-flex">
      <button  class="btn btn-secondary mx-auto" type="submit">Add Comment</button>
    </div>
  <% end %>

</div>

app/views/gossips/_notice.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/gossips/_tag.html.erb
<p class="tag"><%= tag.title %></p>

app/views/gossips/edit.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>Title of this gossip : <%= @gossip.title%></h1> 
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p><%= alert %></p>
        <ul class="list-unstyled">
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      
    <% end %>
  </div>
  <%= form_for @gossip do |f| %>
    <div class="form-group">
      <label>Gossip's Title</label>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
      <label>Content</label>
      <%= f.text_area :content, class: 'form-control'%>
    </div>
    <div class="form-group">
      <label>Your tag : </label>
      <%= f.select :tags, options_for_select(Tag.all.collect{ |t| [t.title, t.id] }), class: "form-control" %>
    </div>
    <div class="form-group">
      <button  class="btn btn-secondary" type="submit">Update</button>
    </div>
  <% end %>
  <%= link_to "Back" , gossip_path(params[:id]), :class => "btn-custom"%>
</div>

app/views/gossips/index.html.erb
<div class="container">
<div class="jumbotron-fluid">
  <div class="text-center p-3 m-3">
    <h1 class="display-4">Welcome my Friend</h1>
    <p class="lead">Do you want some gossips ?????</p>
    <%= image_tag "https://img.freepik.com/free-vector/woman-whispering-gossip-or-secret-to-her-friend_47649-23.jpg?size=626&ext=jpg", :class => "img-fluid img-goss" %>
    <%= render partial: 'gossips/notice' %>
  </div>
</div>
  
  <% if current_user %>
    <div class="text-center p-2 m-2">
      <h2> ⬇️ This is the last Gossips that we heard ⬇️ </h2> 
    </div>
    <div class="row justify-content-center">
      <div class="btn-custom"><%= link_to "Create a gossip", new_gossip_path %></div>
    </div>
    <div class="row justify-content-center">
      <% @gossips.each do |gossip| %>

        <div class="card gossip-card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name%></h5>
            <hr/>
            <p class="card-text"><%= gossip.title%></p>
            <hr class="hr-custom"/>
            <p class="card-text text-center"><%= gossip.comments.count%> Comments</p>
            <div class="row justify-content-center align-items-center">
              <div class="d-flex gossip-card align-items-center rounded">
                <% pre_like = gossip.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                  <%= button_to '👎', gossip_like_path(gossip, pre_like), method: :delete, class: "m-2 custom-like" %>
                <% else %>
                  <%= button_to '👍', gossip_likes_path(gossip), method: :post, class: "m-2 custom-like" %>
                <% end %> 
                <p class="m-2"><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="btn-custom"><%= link_to "See this gossip", gossip_path(gossip.id)%></div>
            </div>
          </div>
        </div>
      
      <% end %>
    </div>
  <% else %>
    <div class="text-center p-2 m-2">
    
      <h2> ➡️ Please <%= link_to "Login", new_session_path, :class => "new-link" %> to see all the gossips </h2> 
    </div>
  <% end %>

</div>

app/views/gossips/new.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="p-3 m-3">Create a new gossip here</h1>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <p><%= alert %></p>
        <ul class="list-unstyled">
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      
    <% end %>
  </div>
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <div class="row justify-content-center">
        <div class="w-50">
          <div class="form-group">
            <%= label_tag 'Title'%>
            <%= text_field_tag :title, params[:title], class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= label_tag 'Content'%>
            <%= text_area_tag :content, params[:content], class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= label_tag 'Tag'%>
            <%= select_tag :tag, options_for_select(Tag.all.collect{ |u| [u.title, u.id] }), :class => "form-control mb-3" %>
          </div>
          
        </div>
      </div>

      <div class="form-group d-flex">
        <%= submit_tag "Create Gossip", :class => "btn btn-secondary mx-auto" %>
      </div>
    <% end %>

    
  
</div>

app/views/gossips/show.html.erb
<div class="container">
  <div class="text-center p-3 m-3">
    <h1>Title of this gossip : <%= @gossip.title%></h1> 
    <%= render partial: 'gossips/notice' %>
  </div>
  <div class="card gossip-card" style="width: auto;">
    <div class="card-body">
      <h5 class="card-title">Write with ❤️ by <%= @gossip.user.first_name%> <%= @gossip.user.last_name%> ➡️ 
        <%= link_to "See this user", user_path(@gossip.user.id), :class => "new-link"%></h5>
      <h6 class="card-subtitle mb-2 text-muted">Create at : <%= @gossip.created_at%> in 
        <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id), :class => "new-link"%></h6>
      <p class="card-text">Content : <%= @gossip.content%></p>
      <div class="row justify-content-center align-items-center">
        <div class="d-flex gossip-card align-items-center rounded">
          <% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to '👎', gossip_like_path(@gossip, pre_like), method: :delete, class: "m-2 custom-like" %>
          <% else %>
            <%= button_to '👍', gossip_likes_path(@gossip), method: :post, class: "m-2 custom-like" %>
          <% end %> 
          <p class="m-2"><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        </div>
      </div>
      <% if tag?(@gossip) %>
        <%= render partial: 'gossips/tag', collection: @gossip.tags %>
      <% end %>
    </div>
  </div>
  <% if is_creator?(@gossip) %>
    <div class="row justify-content-center">
      <div class="btn-custom-edit m-3"><%= link_to "Edit this gossip", edit_gossip_path(@gossip.id)%></div>
      <%= link_to "Delete this gossip" , gossip_path(@gossip.id), :method => "delete", :class => "btn-custom-delete m-3", :data => {:confirm => "are_you_sure"} %>
    </div>
  <% end %>
  <hr/>
  <%= render partial: 'gossips/form' %>
  <%= render partial: 'gossips/comment', collection: @gossip.comments.reverse %>
</div>